# Generated by Django 3.0.5 on 2020-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besoins', '0002_auto_20200522_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='mail',
            field=models.EmailField(default=None, max_length=254, verbose_name='Entrez votre adresse mail svp'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='allergie',
            field=models.BooleanField(default=None, max_length=3, verbose_name='Avez-vous une allergie ?'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='auxiliaire_vie',
            field=models.BooleanField(default=None, max_length=3, verbose_name="Avez-vous besoin d'un(e) auxiliaire de vie ?"),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='maladie_chronique',
            field=models.BooleanField(default=None, max_length=3, verbose_name='Avez-vous une maladie chronique ?'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='noms_maladie_chronique',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Si vous avez une maladie chronique, quelle est-elle ? '),
        ),
    ]
