# Generated by Django 3.0.5 on 2020-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besoins', '0003_auto_20200522_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Entrez votre adresse mail svp'),
        ),
    ]
