# Generated by Django 3.0.5 on 2020-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('besoins', '0004_auto_20200522_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoin',
            name='mail',
        ),
        migrations.AddField(
            model_name='besoin',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Entrez votre adresse email svp'),
            preserve_default=False,
        ),
    ]
