# Generated by Django 3.0.5 on 2020-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_auto_20200512_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom_sexe_age_foyer',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default=None, max_length=500, verbose_name='Nom prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sexe_age_foyer',
            field=models.CharField(default=None, max_length=500, verbose_name='Age sexe de chaque personne'),
            preserve_default=False,
        ),
    ]
